services:
  spam-classifier:
    build: .
    container_name: spam-ham-classifier
    ports:
      - "8501:8501"
    restart: always
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
